#!/usr/bin/env ruby

require 'csv'
require 'date'
require_relative 'iapd.rb'

DB = 'iapd.db'

# tables_sql = "SELECT name FROM sqlite_master WHERE type='table'"
# tables = `sqlite3 -csv #{DB} "#{tables_sql}" | grep 'ADV_Base_A'`

# There are two variations on CRD numbers
# Columns returned, in order: name, sec file number ,crd
def columns(table_name)
  d = Date.strptime table_name.scan(/_([0-9]+)_[0-9]+/).first.first, '%Y%m%d'
  if d >= Date.new(2017, 10, 1)
    "`1A` as name, `1D` as sec_file_number, `1E1` as crd_number"
  else
    "`1A` as name, `1D` as sec_file_number, `1E` as crd_number"
  end
end

def advisors_in_table(table)
  IAPD.execute "SELECT #{columns(table)} FROM #{table}"
end


advisors = Hash.new({
                      'names' => [],
                      'tables' => [],
                    })

IAPD
  .execute("SELECT name FROM sqlite_master WHERE type='table'")
  .split("\n")
  .select { |t| t.include? "ADV_Base_A" }
  .each do |table|

  advisors_in_table(table).split("\n").each do |row|
    name, sec_file_number, crd_number = row.parse_csv
    advisors[sec_file_number] = advisors[sec_file_number]
                                  
  end
  
end


# tables=$(sqlite3 -csv $db "$tables_sql" | grep 'ADV_Base_A')

# print advisors_in_table('IA_ADV_Base_A_20180101_20180331')
# print IAPD.execute "SELECT name FROM sqlite_master WHERE type='table'"

# while read -r line; do
#     echo "... $line ..."
# done << "$tables"

