#!/usr/bin/env ruby
# arg 1 --> date range
# arg 2 --> create new table instead of select

require 'tempfile'

date_range = ARGV.first ? ARGV.first : '20180401_20180630'

sql = <<SQL
SELECT group_concat(FilingID, '|') as filing_ids, 
       MAX("5F2C") as assets_under_management,
       "1A", "1D", "1E1"
FROM IA_ADV_Base_A_#{date_range}
WHERE "5F2C" >= 1000000000
GROUP BY "1E1", "IA", "1E1", "1D"
ORDER BY assets_under_management desc
SQL

file = Tempfile.new('sql')

begin
  file.write(sql)
  file.rewind

  print `bin/execute-sql-file #{file.path}`

ensure
  file.close!
end
