#!/bin/sh
#
# arg 1 - file path to csv inside zip archive
# arg 2 - destination folder
set -eu

full_file_path="$1"
destination_folder=${2:-data}
file_name=$(echo "$full_file_path" | ruby -n -e 'print $_.split("/")[1]')
destination_file_path="$(readlink -f $destination_folder)/$file_name"

scripts/extract-file "$full_file_path" > "$destination_file_path"
